# Site settings
title: Code Art
tagline: Share with love and passion
email: gayanvirajith@gmail.com
description: >
  Hello I'm Ludovic, a french art coder in web technologies
#baseurl: "/gaya" # the subpath of your site, e.g. /blog/
#url: "http://gayan.me" # the base hostname & protocol for your site
url: "http://localhost:4000" # the base hostname & protocol for your site
logourl: /assets/images/logo.png # Site logo
author: "Ludovic de Luna"
author_thumbnail: "/assets/images/avatar.png" # Author avatar
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#205081" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social: 
    github: ludovicdeluna
    twitter: ludovic_deluna
    #facebook: gayanvirajith
    #gplus: +gayanvirajith
    # dribble: gayanvirajith
    # pinterest: gayanvirajith

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  # disqus_shortname: gaya-webcreate

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: 
  google_webmaster_key: 

# Build settings
#markdown: kramdown
markdown: redcarpet

# Build settings
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
#kramdown:
#  input: GFM
#redcarpet:
#  extensions: ["tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "with_toc_data"]

# Permalinks
permalink:        pretty

# Pagination config
paginate: 5


# FrontMatter default settings
defaults:
  -
    scope:
      type: "posts"
    values:
      permalink: "/:categories/:year/:month/:day/:title/"
      excerpt_separator: "<!--more-->"

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
